---
title: "airbnb-price-detector"
author: "Derek Mingyu MA"
output: html_document
---
```{r setup}
# install.packages("rvest")
# install.packages("httr")
# install.packages("xml2")
# install.packages("RSelenium")
# install.packages("stringr")
library(rvest)
library(httr)
library(xml2)
library(RSelenium)
library(stringr)
```

```{r 2}
getInitialRoomUrlList <- function(city, checkInData, checkOutData, num){
  #each round can get 18 results
  numRound <- num%/%18 + 1
  roomsLink <- vector(mode="character", length=0)
  for (round in 1:numRound){
    base1 <- "https://www.airbnb.com/s/"
    base2 <- "/homes?allow_override%5B%5D=&checkin="
    base3 <- "&checkout="
    base4 <- "&section_offset="
    temp1 <- paste(base1, city, sep = '')
    temp2 <- paste(temp1, base2, sep = '')
    temp3 <- paste(temp2, checkInData, sep = '')
    temp4 <- paste(temp3, base3, sep = '')
    temp5 <- paste(temp4, checkOutData, sep = '')
    if (round == 1){
      queryurl <- temp5
    }else{
      temp6 <- paste(temp5, base4, sep = '')
      queryurl <- paste(temp6, round-1, sep = '')
    }
    queryurl
    session <- read_html(queryurl)
    thisPageResult <- session %>%
      html_nodes(".linkContainer_55zci1")%>%
      html_attr("href")
    roomsLink <- as.vector(rbind(roomsLink,thisPageResult)) 
  }
  result <- data.frame(url = roomsLink[1:num], 
                      city = city,
                      checkInData = checkInData, 
                      checkOutData = checkOutData)
  result
}
```

```{r 3}
rD <- rsDriver()
remDr <- rD[["client"]]
```

```{r getRoomUpdatedInfo}
roomInfo <- function(sublink,remDr) {
  base <- "https://www.airbnb.com"
  url <- paste(base, sublink, sep = '')
  remDr$navigate(url)
  roomNameSrc <- remDr$findElement(value = "//div[@id = 'listing_name']")
  roomName <- roomNameSrc$getElementText()
  roomPriceSrc <- remDr$findElement(value = "//meta[@itemprop = 'price']")
  roomPrice <- roomPriceSrc$getElementAttribute("content")
  roomPriceTotalSrc <- remDr$findElement(value = "//td[@class='text-right']/span[@class = 'text_5mbkop-o_O-size_small_1gg2mc-o_O-weight_bold_153t78d-o_O-inline_g86r3e']")
  roomPriceTotal <- roomPriceTotalSrc$getElementText()
  regexp <- "[[:digit:]]+"
  roomName <- roomName[[1]]
  roomPrice <- roomPrice[[1]]
  roomPriceTotal <- str_extract(roomPriceTotal[1], regexp)
  c(roomName,roomPrice,roomPriceTotal)
}
```

```{r 7}
rD[["server"]]$stop()
```